add password double-entry for encrypting

diff --git a/src/crypt b/src/crypt
--- a/src/crypt
+++ b/src/crypt
@@ -22,7 +22,23 @@
 # THE SOFTWARE.
 
 
+#exit immediately for any failed commands.
+#prevents deleting the cleartext if the encryption command failed,
+#which would leave you with no data
 set -e
+
+
+#get password for en- or de-crypting
+getpass() {
+    #alternative (bash-specific): read -s
+    stty_save=`stty -g` #save terminal settings
+    stty -echo          #turn off echoing
+    read passwd
+    stty $stty_save     #restore settings
+}
+
+
+
 
 #check for `crypt -h`, print and exit
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
@@ -47,17 +63,6 @@ if [ -z "$2" ]; then
 fi
 
 
-#get password for en- or de-crypting
-
-printf "Enter password: "
-#alternative (bash-specific): read -s
-stty_save=`stty -g` #save terminal settings
-stty -echo          #turn off echoing
-read passwd
-stty $stty_save     #restore settings
-
-printf '\n'
-
 
 #to get command-line prompt in gpgv2 and not ncurses-based:
 # > gpg-agent.conf
@@ -69,11 +74,16 @@ printf '\n'
 
 if file -b "$FILE" | grep "GPG.*encrypted" >/dev/null 2>&1; then
     #input file is already encrypted, we are decrypting
+    printf "Decrypting ${FILE}. Enter Password: "
+    getpass
+    printf '\n'
+
     echo "decrypting.."
     gpg --pinentry-mode loopback --passphrase "$passwd" -d -o "${OUTPUT:-${FILE%.gpg}}" "${FILE}"
 
     #if bzipped, we're not done. was probably a dir
     if file -b "${OUTPUT:-${FILE%.gpg}}" | grep "^bzip2" >/dev/null 2>&1; then
+        echo "expanding directory.."
         tar -xjf "${OUTPUT:-${FILE%.gpg}}"
     fi
 
@@ -81,6 +91,19 @@ if file -b "$FILE" | grep "GPG.*encrypted" >/dev/null 2>&1; then
     rm -rf "$FILE"
 
 else
+    printf "Encrypting ${FILE}. Enter Password: "
+    getpass
+    firstpass=$passwd
+    printf '\nRepeat: '
+    getpass
+    printf '\n'
+
+    if [ "$firstpass" != "$passwd" ]; then
+        echo "passwords do not match"
+        exit 1
+    fi
+
+
     #input file is not encrypted, we will encrypt
     echo "encrypting.."
 
